# Build settings
highlighter: rouge

# Site settings
title: "Brain Droppings"
description: > # this means to ignore newlines until "email:"
   Thoughts,examples, and discoveries in software development

email: 81dublin@gmail.com
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Andre Dublin'
author: 'Andre Dublin'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://andredublin.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/andredublin
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/andredublin
    desc:	Fork me on github
    share_url:
    share_title:
    share_link: